extrinsics:
  link6_to_camera:
    translation: [0.09541, -0.0175, 0.02489]
    rotation_ypr: [0.0, -1.04719755, 3.1415926]
    parent: link6
    child: camera_link

  body_to_livox:
    translation: [0.0, 0.0, 0.0]
    rotation_ypr: [0.0, 0.0, 0.0]
    parent: body
    child: livox_frame

  livox_to_base:
    translation: [0.0, -0.29011, -0.075]
    rotation_ypr: [1.5707963, 0.0, 0.0]
    parent: livox_frame
    child: base_link

  base_to_footprint:
    translation: [0.0, 0.0, -0.325]
    rotation_ypr: [0.0, 0.0, 0.0]
    parent: base_link
    child: base_footprint
